-- MySQL Script generated by MySQL Workbench
-- Thu Jan 31 15:12:13 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema news
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `news` ;

-- -----------------------------------------------------
-- Schema news
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `news` DEFAULT CHARACTER SET utf8 ;
USE `news` ;

-- -----------------------------------------------------
-- Table `news`.`user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `news`.`user_role` ;

CREATE TABLE IF NOT EXISTS `news`.`user_role` (
  `ur_id` INT NOT NULL AUTO_INCREMENT,
  `ur_name` VARCHAR(45) NULL,
  PRIMARY KEY (`ur_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `news`.`language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `news`.`language` ;

CREATE TABLE IF NOT EXISTS `news`.`language` (
  `la_id` INT NOT NULL AUTO_INCREMENT,
  `la_name` VARCHAR(45) NULL,
  `la_code` VARCHAR(45) NULL,
  PRIMARY KEY (`la_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `news`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `news`.`user` ;

CREATE TABLE IF NOT EXISTS `news`.`user` (
  `us_id` INT NOT NULL AUTO_INCREMENT,
  `us_name` VARCHAR(45) NULL,
  `us_email` VARCHAR(45) NULL,
  `us_password` VARCHAR(255) NULL,
  `us_blacklisted` TINYINT NULL,
  `us_ur_id` INT NOT NULL,
  `us_la_id` INT NOT NULL,
  PRIMARY KEY (`us_id`),
  INDEX `us_ur_fk_idx` (`us_ur_id` ASC),
  INDEX `us_la_fk_idx` (`us_la_id` ASC),
  CONSTRAINT `us_ur_fk`
    FOREIGN KEY (`us_ur_id`)
    REFERENCES `news`.`user_role` (`ur_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `us_la_fk`
    FOREIGN KEY (`us_la_id`)
    REFERENCES `news`.`language` (`la_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `news`.`article`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `news`.`article` ;

CREATE TABLE IF NOT EXISTS `news`.`article` (
  `ar_id` INT NOT NULL AUTO_INCREMENT,
  `ar_author` VARCHAR(255) NULL,
  `ar_title` VARCHAR(2550) NULL,
  `ar_description` VARCHAR(2550) NULL,
  `ar_url` VARCHAR(2550) NULL,
  `ar_url_to_image` VARCHAR(2550) NULL,
  `ar_content` VARCHAR(10000) NULL,
  PRIMARY KEY (`ar_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `news`.`favourite_article`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `news`.`favourite_article` ;

CREATE TABLE IF NOT EXISTS `news`.`favourite_article` (
  `fa_id` INT NOT NULL AUTO_INCREMENT,
  `fa_us_id` INT NOT NULL,
  `fa_ar_id` INT NOT NULL,
  PRIMARY KEY (`fa_id`),
  INDEX `fa_us_fk_idx` (`fa_us_id` ASC),
  INDEX `fa_ar_fk_idx` (`fa_ar_id` ASC),
  CONSTRAINT `fa_us_fk`
    FOREIGN KEY (`fa_us_id`)
    REFERENCES `news`.`user` (`us_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fa_ar_fk`
    FOREIGN KEY (`fa_ar_id`)
    REFERENCES `news`.`article` (`ar_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
